#if !canImport(ObjectiveC)
import XCTest

extension FirebladeUUIDTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__FirebladeUUIDTests = [
        ("testInit", testInit),
        ("testString", testString),
        ("testUniqueness", testUniqueness),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(FirebladeUUIDTests.__allTests__FirebladeUUIDTests),
    ]
}
#endif
