name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  macOS:
    runs-on: macOS-latest
    strategy:
      matrix:
        xcode: ["11.7", "12.3"]
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Select Xcode ${{ matrix.xcode }}
        run: sudo xcode-select -s /Applications/Xcode_${{ matrix.xcode }}.app
      - name: Swift version
        run: swift --version
      - name: Test
        run: swift test -v --skip-update --parallel --enable-test-discovery --enable-code-coverage
        env:
          DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode }}.app/Contents/Developer
      - name: Build Release
        run: swift build -c release
        env:
          DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode }}.app/Contents/Developer

  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        swift: ["5.1", "latest"]
    container:
      image: swift:${{ matrix.swift }}
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: "Update APT"
        shell: bash
        run: "apt update"
      - name: "Install curl"
        shell: bash
        run: "apt-get install -y curl"
      - name: Swift version
        run: swift --version
      - name: Test
        run: swift test -v --skip-update --parallel --enable-test-discovery --enable-code-coverage
      - name: Build Release
        run: swift build -c release
