name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  macOS:
    runs-on: macOS-latest
    strategy:
      matrix:
        xcode: ["13.4.2", "14.2"]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Select Xcode ${{ matrix.xcode }}
        run: sudo xcode-select -s /Applications/Xcode_${{ matrix.xcode }}.app
        
      - name: Test
        run: swift test -v --skip-update --parallel --enable-code-coverage
        env:
          DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode }}.app/Contents/Developer
          
      - name: Build Release
        run: swift build -c release
        env:
          DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode }}.app/Contents/Developer

  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        swift: ["5.1", "latest"]
    container:
      image: swift:${{ matrix.swift }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: "Install dependencies"
        run: | 
          "apt update"
          "apt install -y curl"
          
      - name: Test
        run: swift test -v --parallel --enable-code-coverage
        
      - name: Build Release
        run: swift build -c release
